"""initial schema

Revision ID: 80ac12bd5c83
Revises: 
Create Date: 2026-07-16 12:15:07.485518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ac12bd5c83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('input_period_start', sa.Date(), nullable=True),
    sa.Column('input_period_end', sa.Date(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=10), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('support_start_date', sa.Date(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_assigned_staff_id'), ['assigned_staff_id'], unique=False)

    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_data_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('score_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('life_rhythm_score', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('mental_score', sa.Integer(), nullable=True),
    sa.Column('wellbeing_score', sa.Integer(), nullable=True),
    sa.Column('self_efficacy_score', sa.Integer(), nullable=True),
    sa.Column('work_readiness_score', sa.Integer(), nullable=True),
    sa.Column('stress_status', sa.String(length=10), nullable=True),
    sa.Column('breakdown_json', sa.JSON(), nullable=True),
    sa.Column('calculation_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_score_user_date')
    )
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_results_user_id'), ['user_id'], unique=False)

    op.create_table('staff_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('support_minutes', sa.Integer(), nullable=True),
    sa.Column('support_content', sa.Text(), nullable=True),
    sa.Column('user_condition', sa.Text(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('positive_points', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('behavior_changes', sa.Text(), nullable=True),
    sa.Column('support_method', sa.Text(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('next_check', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_daily_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_daily_reports_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_daily_reports_user_id'), ['user_id'], unique=False)

    op.create_table('support_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_issues', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('user_preferences', sa.Text(), nullable=True),
    sa.Column('background_hypothesis', sa.Text(), nullable=True),
    sa.Column('long_term_goal', sa.Text(), nullable=True),
    sa.Column('short_term_goals_json', sa.JSON(), nullable=True),
    sa.Column('support_methods_json', sa.JSON(), nullable=True),
    sa.Column('home_actions_json', sa.JSON(), nullable=True),
    sa.Column('office_actions_json', sa.JSON(), nullable=True),
    sa.Column('user_actions_json', sa.JSON(), nullable=True),
    sa.Column('evaluation_metrics_json', sa.JSON(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_plans_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value_json', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('user_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('bedtime', sa.String(length=5), nullable=True),
    sa.Column('wake_time', sa.String(length=5), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('breakfast_status', sa.String(length=10), nullable=True),
    sa.Column('lunch_status', sa.String(length=10), nullable=True),
    sa.Column('dinner_status', sa.String(length=10), nullable=True),
    sa.Column('exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('work_study_minutes', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('fatigue_level', sa.Integer(), nullable=True),
    sa.Column('social_level', sa.Integer(), nullable=True),
    sa.Column('achievement', sa.Text(), nullable=True),
    sa.Column('success_experience', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('tomorrow_goal', sa.Text(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_date', name='uq_user_report_date')
    )
    with op.batch_alter_table('user_daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_reports_user_id'), ['user_id'], unique=False)

    op.create_table('support_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_content', sa.Text(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('effect_score', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_actions_support_plan_id'), ['support_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_actions_user_id'), ['user_id'], unique=False)

    op.create_table('support_plan_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_plan_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_plan_versions_support_plan_id'), ['support_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plan_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_plan_versions_support_plan_id'))

    op.drop_table('support_plan_versions')
    with op.batch_alter_table('support_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_actions_support_plan_id'))

    op.drop_table('support_actions')
    with op.batch_alter_table('user_daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_reports_user_id'))

    op.drop_table('user_daily_reports')
    op.drop_table('system_settings')
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_plans_user_id'))

    op.drop_table('support_plans')
    with op.batch_alter_table('staff_daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_daily_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_daily_reports_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_daily_reports_report_date'))

    op.drop_table('staff_daily_reports')
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_results_user_id'))

    op.drop_table('score_results')
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_alerts_status'))

    op.drop_table('risk_alerts')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_assigned_staff_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    op.drop_table('goals')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_created_at'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
